// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjrguxtbivtsxvwlzyqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcmd1eHRiaXZ0c3h2d2x6eXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTQ2NjUsImV4cCI6MjA1ODg5MDY2NX0.IlEMaOhET5qIr4ZcmaszXM9jj6Td_PHa9skKG4kPtUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);